version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    time: "12:00"
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/backend"
  schedule:
    interval: weekly
    time: "12:00"
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/frontend"
  schedule:
    interval: weekly
    time: "12:00"
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/common"
  schedule:
    interval: weekly
    time: "12:00"
  open-pull-requests-limit: 10